// src/app/school/students/mockData.ts
import { Gender, NigerianState, ExamType, UserRole, DeactivationType } from "@/utils/enums";
import type { StudentWithUser } from "./types";

export const MOCK_STUDENTS: StudentWithUser[] = [
  {
    user: {
      id: "550e8400-e29b-41d4-a716-446655440000",
      firstName: "Adebayo",
      middleName: "Oluwaseun",
      lastName: "Ogunlesi",
      email: "adebayo.ogunlesi@example.com",
      phoneNumber: "+2348123456789",
      dateOfBirth: new Date("2006-05-15"),
      gender: Gender.MALE,
      stateOfResidence: NigerianState.LAGOS,
      lga: "Ikeja",
      avatarUrl: null,
      bio: "Aspiring software engineer and passionate about mathematics. I love solving complex problems and helping my peers understand difficult concepts.",
      role: UserRole.STUDENT,
      isEmailVerified: true,
      isPhoneVerified: true,
      isActive: true,
      isOnboarded: true,
      lastLoginAt: new Date("2026-06-06T08:30:00"),
      totalLoginCount: 245,
      referralCode: "BAYO2024",
      referredByCode: null,
      createdAt: new Date("2025-01-15T10:00:00"),
      updatedAt: new Date("2026-06-05T14:20:00"),
    },
    studentProfile: {
      id: "660e8400-e29b-41d4-a716-446655440001",
      currentSchool: "Lagos State Model College",
      currentClass: "SS3 Science",
      graduationYear: 2026,
      admissionNo: "LMC/SS3/001",
      examTargets: [ExamType.JAMB, ExamType.WAEC],
      examDate: new Date("2026-05-15"),
      targetScore: 380,
      targetUniversity: "University of Lagos (UNILAG)",
      targetCourse: "Computer Science",
      focusSubjects: ["Mathematics", "Physics", "Chemistry", "English"],
      totalXp: 2750,
      level: 5,
      levelTitle: "Expert",
      totalBadges: 12,
      streakShields: 2,
      currentStreak: 15,
      longestStreak: 28,
      lastStudyDate: new Date("2026-06-06"),
      averageScore: 85.6,
      totalQuestionsAttempted: 3450,
      totalQuestionsCorrect: 2953,
      totalExamsTaken: 28,
      totalMinutesStudied: 3240,
      bestScore: 96,
      worstScore: 72,
      subjectPerformance: {
        Mathematics: {
          averageScore: 88,
          questionsAttempted: 850,
          questionsCorrect: 748,
          totalMinutes: 780,
          lastPracticedAt: "2026-06-05T10:00:00Z",
        },
        Physics: {
          averageScore: 82,
          questionsAttempted: 720,
          questionsCorrect: 590,
          totalMinutes: 690,
          lastPracticedAt: "2026-06-04T14:30:00Z",
        },
        Chemistry: {
          averageScore: 86,
          questionsAttempted: 680,
          questionsCorrect: 585,
          totalMinutes: 650,
          lastPracticedAt: "2026-06-06T09:00:00Z",
        },
        English: {
          averageScore: 84,
          questionsAttempted: 600,
          questionsCorrect: 504,
          totalMinutes: 550,
          lastPracticedAt: "2026-06-03T11:15:00Z",
        },
      },
      examPerformance: {
        JAMB: {
          examsTaken: 8,
          bestScore: 92,
          worstScore: 78,
          averageScore: 85,
          lastAttemptAt: "2026-05-20T10:00:00Z",
        },
        WAEC: {
          examsTaken: 6,
          bestScore: 96,
          worstScore: 75,
          averageScore: 86,
          lastAttemptAt: "2026-05-25T09:30:00Z",
        },
      },
      leaderboardRank: 42,
      percentileStanding: 95.5,
      parentPhone: "+2348023456789",
      parentName: "Mr. Olumide Ogunlesi",
      socialLinks: {
        twitter: "@adebayo_dev",
        instagram: "@adebayo_code",
        linkedin: "linkedin.com/in/adebayo",
        youtube: null,
      },
      createdAt: new Date("2025-01-15T10:00:00"),
      updatedAt: new Date("2026-06-06T12:00:00"),
      schoolId: null,
      schoolClassId: null,
      weakTopics: [],
      streakHistory: [],
      studyActivities: [],
      topicMasteryHistory: [],
      examSessions: [],
    },
  },
  {
    user: {
      id: "550e8400-e29b-41d4-a716-446655440002",
      firstName: "Chiamaka",
      middleName: "Grace",
      lastName: "Nwachukwu",
      email: "chiamaka.nwachukwu@example.com",
      phoneNumber: "+2348165432109",
      dateOfBirth: new Date("2007-02-20"),
      gender: Gender.FEMALE,
      stateOfResidence: NigerianState.ANAMBRA,
      lga: "Awka South",
      avatarUrl: null,
      bio: "Aspiring medical doctor with a passion for biology and chemistry. I enjoy learning about the human body and helping others.",
      role: UserRole.STUDENT,
      isEmailVerified: true,
      isPhoneVerified: true,
      isActive: true,
      isOnboarded: true,
      lastLoginAt: new Date("2026-06-06T15:45:00"),
      totalLoginCount: 187,
      referralCode: "CHI2024",
      referredByCode: "BAYO2024",
      createdAt: new Date("2025-02-10T11:30:00"),
      updatedAt: new Date("2026-06-05T16:20:00"),
    },
    studentProfile: {
      id: "660e8400-e29b-41d4-a716-446655440003",
      currentSchool: "Queens College",
      currentClass: "SS3 Science",
      graduationYear: 2026,
      admissionNo: "QC/SS3/042",
      examTargets: [ExamType.JAMB, ExamType.WAEC, ExamType.NECO],
      examDate: new Date("2026-05-10"),
      targetScore: 390,
      targetUniversity: "University of Nigeria, Nsukka (UNN)",
      targetCourse: "Medicine and Surgery",
      focusSubjects: ["Biology", "Chemistry", "Physics", "Mathematics"],
      totalXp: 3240,
      level: 6,
      levelTitle: "Master",
      totalBadges: 15,
      streakShields: 3,
      currentStreak: 21,
      longestStreak: 35,
      lastStudyDate: new Date("2026-06-05"),
      averageScore: 89.2,
      totalQuestionsAttempted: 4120,
      totalQuestionsCorrect: 3675,
      totalExamsTaken: 35,
      totalMinutesStudied: 3980,
      bestScore: 98,
      worstScore: 75,
      subjectPerformance: {
        Biology: {
          averageScore: 94,
          questionsAttempted: 1200,
          questionsCorrect: 1128,
          totalMinutes: 1100,
          lastPracticedAt: "2026-06-05T13:00:00Z",
        },
        Chemistry: {
          averageScore: 87,
          questionsAttempted: 980,
          questionsCorrect: 853,
          totalMinutes: 950,
          lastPracticedAt: "2026-06-04T10:30:00Z",
        },
        Physics: {
          averageScore: 84,
          questionsAttempted: 850,
          questionsCorrect: 714,
          totalMinutes: 820,
          lastPracticedAt: "2026-06-03T15:45:00Z",
        },
      },
      examPerformance: {
        JAMB: {
          examsTaken: 10,
          bestScore: 96,
          worstScore: 82,
          averageScore: 89,
          lastAttemptAt: "2026-05-18T11:00:00Z",
        },
        WAEC: {
          examsTaken: 8,
          bestScore: 98,
          worstScore: 80,
          averageScore: 90,
          lastAttemptAt: "2026-05-22T09:00:00Z",
        },
        NECO: {
          examsTaken: 5,
          bestScore: 94,
          worstScore: 85,
          averageScore: 89,
          lastAttemptAt: "2026-05-28T14:00:00Z",
        },
      },
      leaderboardRank: 18,
      percentileStanding: 98.2,
      parentPhone: "+2348034567890",
      parentName: "Prof. Ngozi Nwachukwu",
      socialLinks: {
        twitter: "@chiamaka_med",
        instagram: "@chiamaka_grace",
        linkedin: null,
        youtube: null,
      },
      createdAt: new Date("2025-02-10T11:30:00"),
      updatedAt: new Date("2026-06-05T16:20:00"),
      schoolId: null,
      schoolClassId: null,
      weakTopics: [],
      streakHistory: [],
      studyActivities: [],
      topicMasteryHistory: [],
      examSessions: [],
    },
  },
  {
    user: {
      id: "550e8400-e29b-41d4-a716-446655440004",
      firstName: "Ibrahim",
      middleName: "Abdullahi",
      lastName: "Bello",
      email: "ibrahim.bello@example.com",
      phoneNumber: "+2348098765432",
      dateOfBirth: new Date("2006-11-08"),
      gender: Gender.MALE,
      stateOfResidence: NigerianState.KADUNA,
      lga: "Kaduna North",
      avatarUrl: null,
      bio: "Aspiring engineer with a passion for physics and technical drawing. I love building things and understanding how they work.",
      role: UserRole.STUDENT,
      isEmailVerified: true,
      isPhoneVerified: false,
      isActive: true,
      isOnboarded: true,
      lastLoginAt: new Date("2026-06-05T10:15:00"),
      totalLoginCount: 132,
      referralCode: "IBR2024",
      referredByCode: null,
      createdAt: new Date("2025-03-20T09:45:00"),
      updatedAt: new Date("2026-06-04T11:30:00"),
    },
    studentProfile: {
      id: "660e8400-e29b-41d4-a716-446655440005",
      currentSchool: "Government Secondary School",
      currentClass: "SS2 Science",
      graduationYear: 2027,
      admissionNo: "GSS/SS2/089",
      examTargets: [ExamType.JAMB, ExamType.WAEC],
      examDate: new Date("2027-05-15"),
      targetScore: 350,
      targetUniversity: "Ahmadu Bello University (ABU)",
      targetCourse: "Mechanical Engineering",
      focusSubjects: ["Physics", "Mathematics", "Further Mathematics", "Technical Drawing"],
      totalXp: 1820,
      level: 4,
      levelTitle: "Achiever",
      totalBadges: 7,
      streakShields: 1,
      currentStreak: 8,
      longestStreak: 14,
      lastStudyDate: new Date("2026-06-04"),
      averageScore: 78.3,
      totalQuestionsAttempted: 2150,
      totalQuestionsCorrect: 1683,
      totalExamsTaken: 18,
      totalMinutesStudied: 2100,
      bestScore: 88,
      worstScore: 65,
      subjectPerformance: {
        Physics: {
          averageScore: 82,
          questionsAttempted: 650,
          questionsCorrect: 533,
          totalMinutes: 620,
          lastPracticedAt: "2026-06-04T09:30:00Z",
        },
        Mathematics: {
          averageScore: 76,
          questionsAttempted: 700,
          questionsCorrect: 532,
          totalMinutes: 680,
          lastPracticedAt: "2026-06-03T14:15:00Z",
        },
      },
      examPerformance: {
        JAMB: {
          examsTaken: 5,
          bestScore: 85,
          worstScore: 68,
          averageScore: 76,
          lastAttemptAt: "2026-05-25T10:30:00Z",
        },
      },
      leaderboardRank: 156,
      percentileStanding: 72.8,
      parentPhone: "+2347065432109",
      parentName: "Alhaji Abdullahi Bello",
      socialLinks: {
        twitter: "@ibrahim_eng",
        instagram: null,
        linkedin: null,
        youtube: null,
      },
      createdAt: new Date("2025-03-20T09:45:00"),
      updatedAt: new Date("2026-06-04T11:30:00"),
      schoolId: null,
      schoolClassId: null,
      weakTopics: [],
      streakHistory: [],
      studyActivities: [],
      topicMasteryHistory: [],
      examSessions: [],
    },
  },
  {
    user: {
      id: "550e8400-e29b-41d4-a716-446655440006",
      firstName: "Oluwafunmilayo",
      middleName: "Esther",
      lastName: "Adekunle",
      email: "funmilayo.adekunle@example.com",
      phoneNumber: "+2348134567890",
      dateOfBirth: new Date("2007-07-25"),
      gender: Gender.FEMALE,
      stateOfResidence: NigerianState.OGUN,
      lga: "Abeokuta South",
      avatarUrl: null,
      bio: "Aspiring lawyer and public speaker. I love literature, government, and debating current affairs.",
      role: UserRole.STUDENT,
      isEmailVerified: true,
      isPhoneVerified: true,
      isActive: false,
      isOnboarded: true,
      lastLoginAt: new Date("2026-05-20T14:30:00"),
      totalLoginCount: 89,
      referralCode: "FUNMI2024",
      referredByCode: "CHI2024",
      deactivatedAt: new Date("2026-05-25T10:00:00"),
      deactivatedBy: "admin@school.com",
      deactivationReason: "Academic break due to family reasons",
      deactivationType: DeactivationType.OTHER,
      createdAt: new Date("2025-04-05T13:15:00"),
      updatedAt: new Date("2026-05-25T10:00:00"),
    },
    studentProfile: {
      id: "660e8400-e29b-41d4-a716-446655440007",
      currentSchool: "International School",
      currentClass: "SS3 Arts",
      graduationYear: 2026,
      admissionNo: "IS/SS3/124",
      examTargets: [ExamType.JAMB, ExamType.WAEC],
      examDate: new Date("2026-05-20"),
      targetScore: 370,
      targetUniversity: "University of Ibadan (UI)",
      targetCourse: "Law",
      focusSubjects: ["English", "Literature", "Government", "CRS"],
      totalXp: 1450,
      level: 3,
      levelTitle: "Scholar",
      totalBadges: 5,
      streakShields: 0,
      currentStreak: 0,
      longestStreak: 12,
      lastStudyDate: new Date("2026-05-20"),
      averageScore: 82.5,
      totalQuestionsAttempted: 1780,
      totalQuestionsCorrect: 1469,
      totalExamsTaken: 14,
      totalMinutesStudied: 1650,
      bestScore: 92,
      worstScore: 71,
      subjectPerformance: {
        English: {
          averageScore: 86,
          questionsAttempted: 450,
          questionsCorrect: 387,
          totalMinutes: 420,
          lastPracticedAt: "2026-05-19T11:00:00Z",
        },
        Literature: {
          averageScore: 85,
          questionsAttempted: 380,
          questionsCorrect: 323,
          totalMinutes: 360,
          lastPracticedAt: "2026-05-18T14:30:00Z",
        },
      },
      examPerformance: {
        JAMB: {
          examsTaken: 4,
          bestScore: 90,
          worstScore: 74,
          averageScore: 82,
          lastAttemptAt: "2026-05-15T09:00:00Z",
        },
      },
      leaderboardRank: 203,
      percentileStanding: 68.5,
      parentPhone: "+2348023456781",
      parentName: "Mrs. Adekunle",
      socialLinks: {
        twitter: "@funmilayo_esq",
        instagram: "@fumnanya_esther",
        linkedin: null,
        youtube: null,
      },
      createdAt: new Date("2025-04-05T13:15:00"),
      updatedAt: new Date("2026-05-20T15:00:00"),
      schoolId: null,
      schoolClassId: null,
      weakTopics: [],
      streakHistory: [],
      studyActivities: [],
      topicMasteryHistory: [],
      examSessions: [],
    },
  },
  {
    user: {
      id: "550e8400-e29b-41d4-a716-446655440008",
      firstName: "Emmanuel",
      middleName: "Chukwudi",
      lastName: "Okonkwo",
      email: "emmanuel.okonkwo@example.com",
      phoneNumber: "+2348109876543",
      dateOfBirth: new Date("2006-09-12"),
      gender: Gender.MALE,
      stateOfResidence: NigerianState.IMO,
      lga: "Owerri Municipal",
      avatarUrl: null,
      bio: "Aspiring data scientist. I love mathematics, statistics, and computer science. Currently learning Python and data analysis.",
      role: UserRole.STUDENT,
      isEmailVerified: true,
      isPhoneVerified: true,
      isActive: true,
      isOnboarded: true,
      lastLoginAt: new Date("2026-06-06T19:20:00"),
      totalLoginCount: 312,
      referralCode: "EMMY2024",
      referredByCode: null,
      createdAt: new Date("2025-01-25T08:00:00"),
      updatedAt: new Date("2026-06-06T20:00:00"),
    },
    studentProfile: {
      id: "660e8400-e29b-41d4-a716-446655440009",
      currentSchool: "Federal Government College",
      currentClass: "SS3 Science",
      graduationYear: 2026,
      admissionNo: "FGC/SS3/056",
      examTargets: [ExamType.JAMB, ExamType.WAEC, ExamType.NECO],
      examDate: new Date("2026-05-05"),
      targetScore: 395,
      targetUniversity: "University of Lagos (UNILAG)",
      targetCourse: "Computer Engineering",
      focusSubjects: ["Mathematics", "Physics", "Chemistry", "Computer Science"],
      totalXp: 4580,
      level: 7,
      levelTitle: "Champion",
      totalBadges: 21,
      streakShields: 5,
      currentStreak: 42,
      longestStreak: 42,
      lastStudyDate: new Date("2026-06-06"),
      averageScore: 92.4,
      totalQuestionsAttempted: 5230,
      totalQuestionsCorrect: 4834,
      totalExamsTaken: 42,
      totalMinutesStudied: 4850,
      bestScore: 100,
      worstScore: 82,
      subjectPerformance: {
        Mathematics: {
          averageScore: 96,
          questionsAttempted: 1500,
          questionsCorrect: 1440,
          totalMinutes: 1350,
          lastPracticedAt: "2026-06-06T08:00:00Z",
        },
        Physics: {
          averageScore: 91,
          questionsAttempted: 1200,
          questionsCorrect: 1092,
          totalMinutes: 1150,
          lastPracticedAt: "2026-06-05T16:30:00Z",
        },
        Chemistry: {
          averageScore: 90,
          questionsAttempted: 1100,
          questionsCorrect: 990,
          totalMinutes: 1050,
          lastPracticedAt: "2026-06-04T11:00:00Z",
        },
        "Computer Science": {
          averageScore: 94,
          questionsAttempted: 800,
          questionsCorrect: 752,
          totalMinutes: 750,
          lastPracticedAt: "2026-06-06T14:15:00Z",
        },
      },
      examPerformance: {
        JAMB: {
          examsTaken: 12,
          bestScore: 98,
          worstScore: 85,
          averageScore: 92,
          lastAttemptAt: "2026-05-10T10:00:00Z",
        },
        WAEC: {
          examsTaken: 10,
          bestScore: 100,
          worstScore: 86,
          averageScore: 93,
          lastAttemptAt: "2026-05-15T09:30:00Z",
        },
        NECO: {
          examsTaken: 6,
          bestScore: 97,
          worstScore: 88,
          averageScore: 93,
          lastAttemptAt: "2026-05-20T14:00:00Z",
        },
      },
      leaderboardRank: 5,
      percentileStanding: 99.5,
      parentPhone: "+2348037890123",
      parentName: "Dr. Chukwuma Okonkwo",
      socialLinks: {
        twitter: "@emmanuel_codes",
        instagram: "@emmy_data",
        linkedin: "linkedin.com/in/emmanuel-okonkwo",
        youtube: "youtube.com/@emmanueltech",
      },
      createdAt: new Date("2025-01-25T08:00:00"),
      updatedAt: new Date("2026-06-06T20:00:00"),
      schoolId: null,
      schoolClassId: null,
      weakTopics: [],
      streakHistory: [],
      studyActivities: [],
      topicMasteryHistory: [],
      examSessions: [],
    },
  },
];

// Helper function to get student by ID
export const getStudentById = (id: string): StudentWithUser | undefined => {
  return MOCK_STUDENTS.find((student) => student.user.id === id);
};

// Helper function to get students by status
export const getStudentsByStatus = (isActive: boolean): StudentWithUser[] => {
  return MOCK_STUDENTS.filter((student) => student.user.isActive === isActive);
};

// Helper function to get students by class
export const getStudentsByClass = (className: string): StudentWithUser[] => {
  return MOCK_STUDENTS.filter((student) => student.studentProfile.currentClass === className);
};
