import { Teacher, TeacherInvitation } from "./types";

export const MOCK_INVITATIONS: TeacherInvitation[] = [
  {
    id: "invite-001",
    email: "tunde.bakare@example.com",
    firstName: "Mr. Tunde",
    lastName: "Bakare",
    role: "TEACHER",
    classIds: ["class-002"],
    invitedBy: "admin-001",
    token: "tok_8f2a1c",
    status: "PENDING",
    expiresAt: new Date("2026-06-29"),
    createdAt: new Date("2026-06-20"),
  },
];

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: "teacher-001",
    userId: "user-001",
    firstName: "Mr. Adebayo",
    lastName: "Ogunlesi",
    email: "adebayo.teacher@example.com",
    phoneNumber: "+234 800 111 2222",
    avatarUrl: null,
    role: "CLASS_ADMIN",
    subjects: ["Mathematics", "Physics"],
    assignedClasses: [
      {
        classId: "class-001",
        className: "SS3 Science",
        classArm: "A",
        role: "CLASS_ADMIN",
        subjects: ["Mathematics", "Physics"],
        assignedAt: new Date("2026-01-10"),
        isActive: true,
      },
      {
        classId: "class-004",
        className: "SS2 Science",
        classArm: "A",
        role: "SUBJECT_TEACHER",
        subjects: ["Mathematics"],
        assignedAt: new Date("2026-02-05"),
        isActive: true,
      },
    ],
    totalExams: 15,
    averageStudentScore: 82.4,
    passRate: 88.2,
    isActive: true,
    lastActive: new Date("2026-06-21"),
    joinedAt: new Date("2026-01-05"),
  },
  {
    id: "teacher-002",
    userId: "user-002",
    firstName: "Mrs. Nkechi",
    lastName: "Okafor",
    email: "nkechi.okafor@example.com",
    phoneNumber: "+234 800 222 3333",
    avatarUrl: null,
    role: "CLASS_ADMIN",
    subjects: ["English", "Literature"],
    assignedClasses: [
      {
        classId: "class-002",
        className: "SS3 Art",
        classArm: "B",
        role: "CLASS_ADMIN",
        subjects: ["English", "Literature"],
        assignedAt: new Date("2026-01-15"),
        isActive: true,
      },
    ],
    totalExams: 10,
    averageStudentScore: 76.8,
    passRate: 79.5,
    isActive: true,
    lastActive: new Date("2026-06-20"),
    joinedAt: new Date("2026-01-10"),
  },
  {
    id: "teacher-003",
    userId: "user-003",
    firstName: "Dr. Michael",
    lastName: "Williams",
    email: "michael.williams@example.com",
    phoneNumber: "+234 800 333 4444",
    avatarUrl: null,
    role: "HEAD_OF_DEPARTMENT",
    subjects: ["Chemistry", "Biology"],
    assignedClasses: [
      {
        classId: "class-001",
        className: "SS3 Science",
        classArm: "A",
        role: "SUBJECT_TEACHER",
        subjects: ["Chemistry"],
        assignedAt: new Date("2026-01-12"),
        isActive: true,
      },
      {
        classId: "class-004",
        className: "SS2 Science",
        classArm: "A",
        role: "SUBJECT_TEACHER",
        subjects: ["Chemistry", "Biology"],
        assignedAt: new Date("2026-02-01"),
        isActive: true,
      },
    ],
    totalExams: 12,
    averageStudentScore: 79.3,
    passRate: 82.5,
    isActive: true,
    lastActive: new Date("2026-06-19"),
    joinedAt: new Date("2026-01-08"),
  },
  {
    id: "teacher-004",
    userId: "user-004",
    firstName: "Mr. Chinedu",
    lastName: "Eze",
    email: "chinedu.eze@example.com",
    phoneNumber: "+234 800 444 5555",
    avatarUrl: null,
    role: "TEACHER",
    subjects: ["Economics", "Commerce", "Accounting"],
    assignedClasses: [
      {
        classId: "class-003",
        className: "SS3 Commercial",
        classArm: null,
        role: "CLASS_ADMIN",
        subjects: ["Economics", "Commerce", "Accounting"],
        assignedAt: new Date("2026-01-20"),
        isActive: true,
      },
    ],
    totalExams: 8,
    averageStudentScore: 71.6,
    passRate: 74.3,
    isActive: true,
    lastActive: new Date("2026-06-18"),
    joinedAt: new Date("2026-01-15"),
  },
  {
    id: "teacher-005",
    userId: "user-005",
    firstName: "Mrs. Grace",
    lastName: "Johnson",
    email: "grace.johnson@example.com",
    phoneNumber: "+234 800 555 6666",
    avatarUrl: null,
    role: "TEACHER",
    subjects: ["English"],
    assignedClasses: [
      {
        classId: "class-005",
        className: "JSS3",
        classArm: "A",
        role: "CLASS_ADMIN",
        subjects: ["English"],
        assignedAt: new Date("2026-02-01"),
        isActive: false,
      },
    ],
    totalExams: 4,
    averageStudentScore: 0,
    passRate: 0,
    isActive: false,
    lastActive: new Date("2026-05-30"),
    joinedAt: new Date("2026-01-20"),
  },
];
