import {
  Hash,
  BookOpen,
  Zap,
  Microscope,
  Heart,
  TrendingUp,
  Landmark,
  PenLine,
  Briefcase,
  Globe,
  Clock,
  Languages,
  Brain,
  Monitor,
  Shield,
  Activity,
  Music,
  Palette,
  Calculator,
  Users,
  Building2,
  Check,
  X,
  Ban,
  BadgeCheck,
  Crown,
  GraduationCap,
  PauseCircleIcon,
} from "lucide-react";
import type { TutorCategory, TutorSpecialization, TutorStatus, VerificationLevel } from "./types";

// ─── SPECIALIZATIONS ────────────────────────────────────────
export const SPECIALIZATIONS: Record<
  TutorSpecialization,
  { label: string; color: string; bg: string; icon: any; category: TutorCategory }
> = {
  mathematics: {
    label: "Mathematics",
    color: "#2e8b57",
    bg: "#2e8b5715",
    icon: Hash,
    category: "secondary",
  },
  english: {
    label: "English",
    color: "#3b82f6",
    bg: "#3b82f615",
    icon: BookOpen,
    category: "secondary",
  },
  physics: {
    label: "Physics",
    color: "#ef4444",
    bg: "#ef444415",
    icon: Zap,
    category: "secondary",
  },
  chemistry: {
    label: "Chemistry",
    color: "#8b5cf6",
    bg: "#8b5cf615",
    icon: Microscope,
    category: "secondary",
  },
  biology: {
    label: "Biology",
    color: "#10b981",
    bg: "#10b98115",
    icon: Heart,
    category: "secondary",
  },
  economics: {
    label: "Economics",
    color: "#f59e0b",
    bg: "#f59e0b15",
    icon: TrendingUp,
    category: "secondary",
  },
  government: {
    label: "Government",
    color: "#6366f1",
    bg: "#6366f115",
    icon: Landmark,
    category: "secondary",
  },
  literature: {
    label: "Literature",
    color: "#ec4899",
    bg: "#ec489915",
    icon: PenLine,
    category: "secondary",
  },
  commerce: {
    label: "Commerce",
    color: "#14b8a6",
    bg: "#14b8a615",
    icon: Briefcase,
    category: "secondary",
  },
  geography: {
    label: "Geography",
    color: "#f97316",
    bg: "#f9731615",
    icon: Globe,
    category: "secondary",
  },
  history: {
    label: "History",
    color: "#a855f7",
    bg: "#a855f715",
    icon: Clock,
    category: "secondary",
  },
  french: {
    label: "French",
    color: "#06b6d4",
    bg: "#06b6d415",
    icon: Languages,
    category: "secondary",
  },
  yoruba: {
    label: "Yoruba",
    color: "#84cc16",
    bg: "#84cc1615",
    icon: Languages,
    category: "secondary",
  },
  hausa: {
    label: "Hausa",
    color: "#eab308",
    bg: "#eab30815",
    icon: Languages,
    category: "secondary",
  },
  igbo: {
    label: "Igbo",
    color: "#22c55e",
    bg: "#22c55e15",
    icon: Languages,
    category: "secondary",
  },
  agriculture: {
    label: "Agriculture",
    color: "#15803d",
    bg: "#15803d15",
    icon: BookOpen,
    category: "secondary",
  },
  technical_drawing: {
    label: "Technical Drawing",
    color: "#475569",
    bg: "#47556915",
    icon: PenLine,
    category: "secondary",
  },
  further_mathematics: {
    label: "Further Maths",
    color: "#7c3aed",
    bg: "#7c3aed15",
    icon: Brain,
    category: "secondary",
  },
  computer_studies: {
    label: "Computer Studies",
    color: "#0891b2",
    bg: "#0891b215",
    icon: Monitor,
    category: "secondary",
  },
  civic_education: {
    label: "Civic Education",
    color: "#dc2626",
    bg: "#dc262615",
    icon: Shield,
    category: "secondary",
  },
  business_studies: {
    label: "Business Studies",
    color: "#ca8a04",
    bg: "#ca8a0415",
    icon: Briefcase,
    category: "secondary",
  },
  home_economics: {
    label: "Home Economics",
    color: "#be185d",
    bg: "#be185d15",
    icon: Heart,
    category: "secondary",
  },
  physical_education: {
    label: "PHE",
    color: "#1d4ed8",
    bg: "#1d4ed815",
    icon: Activity,
    category: "secondary",
  },
  music: { label: "Music", color: "#9333ea", bg: "#9333ea15", icon: Music, category: "secondary" },
  fine_arts: {
    label: "Fine Arts",
    color: "#c2410c",
    bg: "#c2410c15",
    icon: Palette,
    category: "secondary",
  },
  accounting: {
    label: "Accounting",
    color: "#0891b2",
    bg: "#0891b215",
    icon: Calculator,
    category: "professional",
  },
  nursing: {
    label: "Nursing",
    color: "#dc2626",
    bg: "#dc262615",
    icon: Heart,
    category: "professional",
  },
  hr_management: {
    label: "HR Management",
    color: "#7c3aed",
    bg: "#7c3aed15",
    icon: Users,
    category: "professional",
  },
  estate_management: {
    label: "Estate Management",
    color: "#d97706",
    bg: "#d9770615",
    icon: Building2,
    category: "professional",
  },
};

// ─── STATUS CONFIG ───────────────────────────────────────────
export const STATUS_CONFIG: Record<
  TutorStatus,
  { label: string; bg: string; text: string; icon: any }
> = {
  active: { label: "Active", bg: "#10b98115", text: "#10b981", icon: Check },
  inactive: { label: "Inactive", bg: "#6b728015", text: "#6b7280", icon: X },
  suspended: { label: "Suspended", bg: "#ef444415", text: "#ef4444", icon: Ban },
  pending: { label: "Pending", bg: "#f59e0b15", text: "#f59e0b", icon: Clock },
  on_leave: { label: "On Leave", bg: "#3b82f615", text: "#3b82f6", icon: PauseCircleIcon },
};

// ─── VERIFICATION CONFIG ─────────────────────────────────────
export const VERIFICATION_CONFIG: Record<
  VerificationLevel,
  { label: string; bg: string; text: string; icon: any }
> = {
  verified: { label: "Verified", bg: "#10b98115", text: "#10b981", icon: BadgeCheck },
  unverified: { label: "Unverified", bg: "#6b728015", text: "#6b7280", icon: Shield },
  pending: { label: "Pending", bg: "#f59e0b15", text: "#f59e0b", icon: Clock },
  premium: { label: "Premium", bg: "#8b5cf615", text: "#8b5cf6", icon: Crown },
};

// ─── CATEGORY CONFIG ─────────────────────────────────────────
export const CATEGORY_CONFIG: Record<
  TutorCategory,
  { label: string; icon: any; color: string; bg: string }
> = {
  secondary: { label: "Secondary School", icon: GraduationCap, color: "#2e8b57", bg: "#2e8b5715" },
  professional: { label: "Professional", icon: Briefcase, color: "#7c3aed", bg: "#7c3aed15" },
};

// ─── NIGERIAN STATES ─────────────────────────────────────────
export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const DEFAULT_FILTERS = {
  status: "" as const,
  verification: "" as const,
  specialization: "",
  state: "",
  teachingMode: "" as const,
  minRating: "",
  minExperience: "",
  maxExperience: "",
  minRate: "",
  maxRate: "",
  isOnline: "",
};
