import {
  Bell,
  Shield,
  Users,
  School,
  CreditCard,
  AlertTriangle,
  TrendingUp,
  Server,
  Database,
  CheckCircle,
  Activity,
  Zap,
  Lock,
  RefreshCw,
} from "lucide-react";
import type {
  AdminNotificationType,
  NotificationPriority,
  NotificationFilter,
  AdminNotification,
} from "./types";

// ─── TYPE CONFIG ──────────────────────────────────────────────
export const NOTIFICATION_TYPE_CONFIG: Record<
  AdminNotificationType,
  { icon: any; color: string; bg: string; label: string; category: string }
> = {
  user_signup: {
    icon: Users,
    color: "#2e8b57",
    bg: "#e8f5e9",
    label: "User Signup",
    category: "users",
  },
  user_report: {
    icon: Shield,
    color: "#f59e0b",
    bg: "#fed7aa",
    label: "User Report",
    category: "users",
  },
  payment_dispute: {
    icon: AlertTriangle,
    color: "#ef4444",
    bg: "#fee2e2",
    label: "Payment Dispute",
    category: "payments",
  },
  school_onboarded: {
    icon: School,
    color: "#8b5cf6",
    bg: "#ede9fe",
    label: "School Onboarded",
    category: "schools",
  },
  system_alert: {
    icon: AlertTriangle,
    color: "#ef4444",
    bg: "#fee2e2",
    label: "System Alert",
    category: "system",
  },
  backup_completed: {
    icon: Database,
    color: "#10b981",
    bg: "#d1fae5",
    label: "Backup Done",
    category: "system",
  },
  high_usage_alert: {
    icon: TrendingUp,
    color: "#f59e0b",
    bg: "#fed7aa",
    label: "Usage Alert",
    category: "system",
  },
  fraud_alert: {
    icon: Lock,
    color: "#ef4444",
    bg: "#fee2e2",
    label: "Fraud Alert",
    category: "security",
  },
  subscription_expiring: {
    icon: CreditCard,
    color: "#f59e0b",
    bg: "#fed7aa",
    label: "Sub. Expiring",
    category: "payments",
  },
  server_status: {
    icon: Server,
    color: "#3b82f6",
    bg: "#dbeafe",
    label: "Server Status",
    category: "system",
  },
  database_backup: {
    icon: Database,
    color: "#10b981",
    bg: "#d1fae5",
    label: "DB Backup",
    category: "system",
  },
  new_feature: {
    icon: Zap,
    color: "#8b5cf6",
    bg: "#ede9fe",
    label: "New Feature",
    category: "platform",
  },
  admin_action: {
    icon: Shield,
    color: "#6b7280",
    bg: "#f3f4f6",
    label: "Admin Action",
    category: "admin",
  },
};

// ─── PRIORITY CONFIG ──────────────────────────────────────────
export const PRIORITY_CONFIG: Record<
  NotificationPriority,
  { label: string; color: string; bg: string; textClass: string }
> = {
  high: { label: "Urgent", color: "#ef4444", bg: "#fee2e2", textClass: "text-red-600" },
  medium: { label: "Medium", color: "#f97316", bg: "#ffedd5", textClass: "text-orange-600" },
  low: { label: "Low", color: "#10b981", bg: "#d1fae5", textClass: "text-green-600" },
};

// ─── FILTER LABELS ────────────────────────────────────────────
export const FILTER_CONFIG: {
  key: NotificationFilter;
  label: string;
  color: string;
}[] = [
  { key: "all", label: "All", color: "#2e8b57" },
  { key: "unread", label: "Unread", color: "#3b82f6" },
  { key: "read", label: "Resolved", color: "#10b981" },
  { key: "archived", label: "Archived", color: "#6b7280" },
  { key: "high", label: "Urgent", color: "#ef4444" },
  { key: "medium", label: "Medium Priority", color: "#f97316" },
  { key: "low", label: "Low Priority", color: "#10b981" },
];

// ─── RICH MOCK DATA ───────────────────────────────────────────
export const MOCK_ADMIN_NOTIFICATIONS: AdminNotification[] = [
  {
    id: "1",
    type: "fraud_alert",
    title: "Fraud Alert: Suspicious Transaction",
    body: "Transaction TX-2024-8821 flagged with risk score 97/100. Immediate review required.",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    status: "unread",
    priority: "high",
    actionUrl: "/admin/transactions",
    metadata: { transactionId: "TX-2024-8821", riskScore: 97, amount: 150000 },
  },
  {
    id: "2",
    type: "payment_dispute",
    title: "Payment Dispute Opened",
    body: "Chioma Eze has disputed a ₦2,500 subscription charge. Resolution required within 48 hours.",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    status: "unread",
    priority: "high",
    actionUrl: "/admin/transactions",
    metadata: { transactionId: "tx_456", amount: 2500, userId: "usr_002" },
  },
  {
    id: "3",
    type: "server_status",
    title: "Server Performance Degraded",
    body: "API response times averaging 2.5s — above the 1s threshold. 14% of requests timing out.",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    status: "unread",
    priority: "high",
    actionUrl: "/admin/system",
    metadata: { responseTime: "2.5s", threshold: "1s", errorRate: "14%" },
  },
  {
    id: "4",
    type: "school_onboarded",
    title: "New School Onboarded",
    body: "Lagos Preparatory School has completed onboarding with 450 students and 12 classes.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: "unread",
    priority: "medium",
    actionUrl: "/admin/schools",
    metadata: { schoolId: "school_789", studentCount: 450, classCount: 12 },
  },
  {
    id: "5",
    type: "user_signup",
    title: "New User Registrations: 48 Today",
    body: "48 new students and 3 tutors registered today. This is 22% above the daily average.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    status: "unread",
    priority: "medium",
    actionUrl: "/admin/users",
    metadata: { students: 48, tutors: 3, avgDailySignups: 39 },
  },
  {
    id: "6",
    type: "high_usage_alert",
    title: "AI API Usage 200% Above Normal",
    body: "AI essay marking has consumed 12,000 tokens today vs a normal of 4,000. Review AI logs.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    status: "unread",
    priority: "high",
    actionUrl: "/admin/ai-logs",
    metadata: { currentUsage: 12000, normalUsage: 4000, costUSD: 24 },
  },
  {
    id: "7",
    type: "user_report",
    title: "User Report: Inappropriate Content",
    body: "A tutor profile has been reported 3 times for inappropriate content. Review needed.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    status: "unread",
    priority: "medium",
    actionUrl: "/admin/users",
    metadata: { tutorId: "tut_091", reportCount: 3 },
  },
  {
    id: "8",
    type: "backup_completed",
    title: "Daily Backup Completed",
    body: "Database backup (2.4 GB) completed in 5 min 12 sec. Stored to offsite S3 bucket.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    status: "read",
    priority: "low",
    actionUrl: "/admin/settings/backup",
    metadata: { size: "2.4GB", duration: "5m 12s", bucket: "gravitas-backups-ng" },
  },
  {
    id: "9",
    type: "subscription_expiring",
    title: "12 School Subscriptions Expiring Soon",
    body: "12 school-tier subscriptions expire in the next 7 days. Total at-risk MRR: ₦1.2M.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    status: "read",
    priority: "medium",
    actionUrl: "/admin/transactions?tab=subscriptions",
    metadata: { count: 12, mrr: 1200000 },
  },
  {
    id: "10",
    type: "new_feature",
    title: "AI Essay Marking Released",
    body: "AI Essay Marking is now live for WAEC students. Monitor adoption and feedback closely.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    status: "read",
    priority: "low",
    actionUrl: "/admin/features",
    metadata: { feature: "ai_essay_marking", rollout: "100%" },
  },
  {
    id: "11",
    type: "system_alert",
    title: "SSL Certificate Expiring in 14 Days",
    body: "The SSL certificate for api.gravitas.ng expires on Feb 10. Renew before expiry.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    status: "unread",
    priority: "high",
    actionUrl: "/admin/system",
    metadata: { domain: "api.gravitas.ng", expiresAt: "2024-02-10" },
  },
  {
    id: "12",
    type: "admin_action",
    title: "Admin Account Created",
    body: "A new super admin account was created for Segun Adeyemi (segun@gravitas.ng).",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    status: "read",
    priority: "medium",
    actionUrl: "/admin/users",
    metadata: { adminEmail: "segun@gravitas.ng", role: "super_admin" },
  },
  {
    id: "13",
    type: "database_backup",
    title: "Weekly Full Backup Complete",
    body: "Weekly full DB backup (18.7 GB) completed. Stored to primary and secondary buckets.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    status: "archived",
    priority: "low",
    actionUrl: "/admin/settings/backup",
    metadata: { size: "18.7GB", duration: "42m", replicas: 2 },
  },
];
