import { QuestionType } from "@/types/practice";
import { SUBJECT_LABEL_TO_ENUM } from "@/utils/subjectMapping";
import {
  BarChart,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  FlaskConical,
  GraduationCap,
  Landmark,
  Library,
  Stethoscope,
  Users,
} from "lucide-react";

export const SECONDARY_EXAMS = [
  {
    id: "JAMB" as const,
    name: "JAMB",
    fullName: "UTME",
    icon: Brain,
    color: "#7c3aed",
    bg: "from-violet-500 to-purple-600",
    description: "Unified Tertiary Matriculation Examination",
    questionTypes: ["MCQ"] as QuestionType[],
    badge: "Most Popular",
  },
  {
    id: "WAEC" as const,
    name: "WAEC",
    fullName: "SSCE",
    icon: BookOpen,
    color: "#0284c7",
    bg: "from-sky-500 to-blue-600",
    description: "West African Senior School Certificate",
    questionTypes: ["MCQ", "THEORY", "PRACTICAL", "ALL"] as QuestionType[],
  },
  {
    id: "NECO" as const,
    name: "NECO",
    fullName: "SSCE",
    icon: Library,
    color: "#059669",
    bg: "from-emerald-500 to-teal-600",
    description: "National Examination Council",
    questionTypes: ["MCQ", "THEORY", "PRACTICAL", "ALL"] as QuestionType[],
  },
  {
    id: "NABTEB" as const,
    name: "NABTEB",
    fullName: "Technical",
    icon: FlaskConical,
    color: "#d97706",
    bg: "from-amber-500 to-orange-500",
    description: "Business & Technical Examinations Board",
    questionTypes: ["MCQ", "THEORY", "PRACTICAL", "ALL"] as QuestionType[],
  },
  {
    id: "BECE" as const,
    name: "BECE",
    fullName: "Junior",
    icon: GraduationCap,
    color: "#16a34a",
    bg: "from-green-500 to-emerald-500",
    description: "Basic Education Certificate Examination",
    questionTypes: ["MCQ", "THEORY"] as QuestionType[],
  },
  {
    id: "JUNIOR_NECO" as const,
    name: "Junior NECO",
    fullName: "JSS",
    icon: Landmark,
    color: "#0d9488",
    bg: "from-teal-500 to-cyan-500",
    description: "Junior Secondary Certificate Examination",
    questionTypes: ["MCQ", "THEORY"] as QuestionType[],
  },
];

export const PROFESSIONAL_EXAMS = [
  {
    id: "ICAN" as const,
    name: "ICAN",
    icon: Calculator,
    color: "#dc2626",
    bg: "from-red-500 to-rose-600",
    description: "Institute of Chartered Accountants of Nigeria",
    levels: ["Foundation", "Skills", "Professional"],
    field: "Accounting & Finance",
  },
  {
    id: "NMCN" as const,
    name: "NMCN",
    icon: Stethoscope,
    color: "#0284c7",
    bg: "from-sky-500 to-blue-600",
    description: "Nursing & Midwifery Council of Nigeria",
    levels: ["Basic", "Post-Basic", "Advanced"],
    field: "Healthcare",
  },
  {
    id: "CIPM" as const,
    name: "CIPM",
    icon: Users,
    color: "#7c3aed",
    bg: "from-violet-500 to-purple-600",
    description: "Chartered Institute of Personnel Management",
    levels: ["Associate", "Chartered", "Fellow"],
    field: "HR & Management",
  },
  {
    id: "NIM" as const,
    name: "NIM",
    icon: Briefcase,
    color: "#d97706",
    bg: "from-amber-500 to-yellow-500",
    description: "Nigerian Institute of Management",
    levels: ["Diploma", "Graduate", "Fellow"],
    field: "Management",
  },
  {
    id: "NIESV" as const,
    name: "NIESV",
    icon: BarChart,
    color: "#059669",
    bg: "from-emerald-500 to-green-600",
    description: "Nigerian Institution of Estate Surveyors & Valuers",
    levels: ["Probationer", "Graduate", "Corporate"],
    field: "Real Estate",
  },
];

// Validates every label at module load — blows up loud in dev if a label drifts
function validated(labels: string[]): string[] {
  if (process.env.NODE_ENV === "development") {
    labels.forEach((label) => {
      if (!SUBJECT_LABEL_TO_ENUM[label]) {
        console.warn(`[SUBJECTS] No enum mapping for label: "${label}"`);
      }
    });
  }
  return labels;
}

export const SUBJECTS: Record<string, string[]> = {
  JAMB: validated([
    "Use of English",
    "Agricultural Science",
    "Arabic",
    "Art (Fine Arts)",
    "Biology",
    "Chemistry",
    "Christian Religious Studies (CRS)",
    "Commerce",
    "Computer Studies / Data Processing",
    "Economics",
    "French",
    "Geography",
    "Government",
    "Hausa",
    "History",
    "Home Economics",
    "Igbo",
    "Islamic Studies (IRK)",
    "Literature in English",
    "Mathematics",
    "Music",
    "Physical & Health Education (PHE)",
    "Physics",
    "Principles of Accounts",
    "Yoruba",
  ]),
  WAEC: validated([
    "English",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Economics",
    "Government",
    "Literature",
    "CRS",
    "IRS",
    "Commerce",
    "Geography",
    "History",
    "Agricultural Science",
    "Further Mathematics",
    "Technical Drawing",
    "Food & Nutrition",
    "Home Economics",
  ]),
  NECO: validated([
    "English",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Economics",
    "Government",
    "Literature",
    "CRS",
    "IRS",
    "Commerce",
    "Geography",
    "History",
    "Agricultural Science",
    "Further Mathematics",
    "Home Economics",
  ]),
  NABTEB: validated([
    "English",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Economics",
    "Technical Drawing",
    "Building Construction",
    "Electrical Installation",
    "Woodwork",
    "Metalwork",
    "Auto Mechanics",
    "Computer Studies",
  ]),
  BECE: validated([
    "English",
    "Mathematics",
    "Basic Science",
    "Social Studies",
    "Civic Education",
    "Christian Studies",
    "Islamic Studies",
    "Home Economics",
    "Agricultural Science",
    "Business Studies",
    "French",
    "CCA",
  ]),
  JUNIOR_NECO: validated([
    "English",
    "Mathematics",
    "Basic Science",
    "Social Studies",
    "Civic Education",
    "PVS",
    "Business Studies",
    "French",
    "CCA",
    "Home Economics",
  ]),
  ICAN_FOUNDATION: validated([
    "Quantitative Techniques in Business",
    "Business and Finance",
    "Financial Accounting",
    "Management Information",
    "Business Law",
  ]),
  ICAN_SKILLS: validated([
    "Audit and Assurance",
    "Financial Reporting",
    "Taxation",
    "Management Accounting",
    "Business Communication and Research Methodology",
  ]),
  ICAN_PROFESSIONAL: validated([
    "Corporate Reporting",
    "Advanced Audit and Assurance",
    "Strategic Financial Management",
    "Advanced Taxation",
    "Ethics and Governance",
  ]),
  NMCN_BASIC: validated([
    "Anatomy and Physiology",
    "Microbiology and Parasitology",
    "Nutrition and Dietetics",
    "Pharmacology",
    "Introduction to Nursing Practice",
    "Community Health Nursing",
  ]),
  NMCN_POST_BASIC: validated([
    "Medical-Surgical Nursing",
    "Paediatric Nursing",
    "Obstetric and Gynaecological Nursing",
    "Mental Health and Psychiatric Nursing",
    "Accident and Emergency Nursing",
  ]),
  NMCN_ADVANCED: validated([
    "Advanced Clinical Nursing",
    "Nursing Research and Education",
    "Nursing Administration and Management",
    "Nurse Prescribing and Pharmacotherapeutics",
    "Midwifery",
  ]),
  CIPM_ASSOCIATE: validated([
    "Organisational Behaviour",
    "Human Resource Management",
    "Employment Law",
    "Learning and Development",
    "Compensation and Benefits Management",
  ]),
  CIPM_CHARTERED: validated([
    "Strategic Human Resource Management",
    "Labour Relations and Collective Bargaining",
    "HR Metrics and Analytics",
    "Organisational Development and Change Management",
    "Performance Management",
  ]),
  CIPM_FELLOW: validated([
    "Leadership and Corporate Governance",
    "Advanced Strategic HRM",
    "HR Consulting and Advisory",
  ]),
  NIM_DIPLOMA: validated([
    "Principles of Management",
    "Business Communication",
    "Economics for Managers",
    "Accounting for Non-Accountants",
    "Marketing Management",
  ]),
  NIM_GRADUATE: validated([
    "Strategic Management",
    "Operations Management",
    "Human Resources Management",
    "Financial Management",
    "Business Law and Ethics",
    "Entrepreneurship and Innovation",
  ]),
  NIM_FELLOW: validated([
    "Corporate Governance",
    "Advanced Strategic Management",
    "Leadership and Executive Development",
    "Research Methods and Project",
  ]),
  NIESV_FOUNDATION: validated([
    "Land Law and Administration",
    "Building Construction and Technology",
    "Valuation Principles",
    "Town Planning and Development Control",
    "Economics of Property",
  ]),
  NIESV_PROFESSIONAL: validated([
    "Advanced Valuation",
    "Property Management",
    "Estate Agency and Marketing",
    "Facilities Management",
    "Dispute Resolution and Arbitration",
    "Real Estate Finance and Investment",
  ]),
};

export const TOPICS: Record<string, string[]> = {
  Mathematics: ["Algebra", "Calculus", "Trigonometry", "Statistics", "Geometry", "Number Theory"],
  Physics: ["Mechanics", "Thermodynamics", "Waves", "Electricity", "Optics", "Modern Physics"],
  Chemistry: [
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Electrochemistry",
    "Equilibrium",
  ],
  Biology: ["Cell Biology", "Genetics", "Ecology", "Evolution", "Human Physiology", "Plants"],
  English: ["Grammar", "Comprehension", "Literature", "Essay Writing", "Oral English"],
  Economics: ["Microeconomics", "Macroeconomics", "International Trade", "Public Finance"],
};
