import { SchoolClass, ClassWithDetails, ClassStudent, ClassAdmin } from "./types";

export const MOCK_CLASSES: SchoolClass[] = [
  {
    id: "class-001",
    schoolId: "school-001",
    name: "SS3 Science",
    arm: "A",
    year: 2025,
    description: "Senior Secondary 3 Science Class - Preparing for JAMB and WAEC",
    classCode: "KCL-SS3SCI-2025",
    pinHash: "hashed_pin_1234",
    pinLastChangedAt: new Date("2025-01-15"),
    defaultExamDurationMinutes: 90,
    defaultQuestionCount: 50,
    totalStudents: 35,
    totalExamsCreated: 12,
    isActive: true,
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "class-002",
    schoolId: "school-001",
    name: "SS3 Art",
    arm: "B",
    year: 2025,
    description: "Senior Secondary 3 Art Class - Literature, Government, CRS",
    classCode: "KCL-SS3ART-2025",
    pinHash: "hashed_pin_5678",
    pinLastChangedAt: new Date("2025-01-20"),
    defaultExamDurationMinutes: 90,
    defaultQuestionCount: 45,
    totalStudents: 28,
    totalExamsCreated: 8,
    isActive: true,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2026-05-28"),
  },
  {
    id: "class-003",
    schoolId: "school-001",
    name: "SS3 Commercial",
    arm: null,
    year: 2025,
    description: "Senior Secondary 3 Commercial Class",
    classCode: "KCL-SS3COMM-2025",
    pinHash: "hashed_pin_9012",
    pinLastChangedAt: new Date("2025-01-18"),
    defaultExamDurationMinutes: 90,
    defaultQuestionCount: 45,
    totalStudents: 30,
    totalExamsCreated: 10,
    isActive: true,
    createdAt: new Date("2025-01-12"),
    updatedAt: new Date("2026-06-02"),
  },
  {
    id: "class-004",
    schoolId: "school-001",
    name: "SS2 Science",
    arm: "A",
    year: 2025,
    description: "Senior Secondary 2 Science Class",
    classCode: "KCL-SS2SCI-2025",
    pinHash: "hashed_pin_3456",
    pinLastChangedAt: new Date("2025-02-10"),
    defaultExamDurationMinutes: 75,
    defaultQuestionCount: 40,
    totalStudents: 38,
    totalExamsCreated: 6,
    isActive: true,
    createdAt: new Date("2025-02-05"),
    updatedAt: new Date("2026-05-30"),
  },
  {
    id: "class-005",
    schoolId: "school-001",
    name: "JSS3",
    arm: "A",
    year: 2025,
    description: "Junior Secondary 3 - Preparation for BECE",
    classCode: "KCL-JSS3A-2025",
    pinHash: "hashed_pin_7890",
    pinLastChangedAt: new Date("2025-03-01"),
    defaultExamDurationMinutes: 60,
    defaultQuestionCount: 40,
    totalStudents: 42,
    totalExamsCreated: 5,
    isActive: false,
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2026-06-01"),
  },
];

export const MOCK_CLASS_STUDENTS: Record<string, ClassStudent[]> = {
  "class-001": [
    {
      id: "1",
      userId: "user-001",
      studentProfileId: "profile-001",
      firstName: "Adebayo",
      lastName: "Ogunlesi",
      email: "adebayo.ogunlesi@example.com",
      admissionNo: "LMC/SS3/001",
      avatarUrl: null,
      joinedAt: new Date("2025-01-15"),
      averageScore: 85.6,
    },
    {
      id: "2",
      userId: "user-002",
      studentProfileId: "profile-002",
      firstName: "Chiamaka",
      lastName: "Nwachukwu",
      email: "chiamaka.nwachukwu@example.com",
      admissionNo: "QC/SS3/042",
      avatarUrl: null,
      joinedAt: new Date("2025-01-20"),
      averageScore: 89.2,
    },
    {
      id: "3",
      userId: "user-003",
      studentProfileId: "profile-003",
      firstName: "Emmanuel",
      lastName: "Okonkwo",
      email: "emmanuel.okonkwo@example.com",
      admissionNo: "FGC/SS3/056",
      avatarUrl: null,
      joinedAt: new Date("2025-01-18"),
      averageScore: 92.4,
    },
    {
      id: "4",
      userId: "user-004",
      studentProfileId: "profile-004",
      firstName: "Oluwafunmilayo",
      lastName: "Adekunle",
      email: "funmilayo.adekunle@example.com",
      admissionNo: "IS/SS3/124",
      avatarUrl: null,
      joinedAt: new Date("2025-01-22"),
      averageScore: 82.5,
    },
    {
      id: "5",
      userId: "user-005",
      studentProfileId: "profile-005",
      firstName: "Ibrahim",
      lastName: "Bello",
      email: "ibrahim.bello@example.com",
      admissionNo: "GSS/SS2/089",
      avatarUrl: null,
      joinedAt: new Date("2025-02-01"),
      averageScore: 78.3,
    },
  ],
  "class-002": [
    {
      id: "6",
      userId: "user-006",
      studentProfileId: "profile-006",
      firstName: "Blessing",
      lastName: "Eze",
      email: "blessing.eze@example.com",
      admissionNo: "QCG/SS3/015",
      avatarUrl: null,
      joinedAt: new Date("2025-01-20"),
      averageScore: 87.5,
    },
  ],
};

export const MOCK_CLASS_ADMINS: Record<string, ClassAdmin[]> = {
  "class-001": [
    {
      id: "admin-001",
      userId: "teacher-001",
      firstName: "Mr. Adebayo",
      lastName: "Ogunlesi",
      email: "adebayo.teacher@example.com",
      role: "CLASS_ADMIN",
      assignedAt: new Date("2025-01-10"),
    },
  ],
  "class-002": [
    {
      id: "admin-002",
      userId: "teacher-002",
      firstName: "Mrs. Okafor",
      lastName: "Nkechi",
      email: "nkechi.okafor@example.com",
      role: "CLASS_ADMIN",
      assignedAt: new Date("2025-01-15"),
    },
  ],
};

export const getClassById = (id: string): ClassWithDetails | undefined => {
  const classData = MOCK_CLASSES.find((c) => c.id === id);
  if (!classData) return undefined;

  return {
    ...classData,
    students: MOCK_CLASS_STUDENTS[id] || [],
    classAdmins: MOCK_CLASS_ADMINS[id] || [],
  };
};
