import {
  Bell, CheckCircle, XCircle, Calendar, MessageSquare, Video,
  CreditCard, Trophy, Flame, BookOpen, AlertTriangle, TrendingUp,
  Mail, Smartphone, Globe, BarChart3,
} from "lucide-react";
import type { NotificationChannel, NotificationType, Notification } from "./types";

// ─── NOTIFICATION TYPE CONFIG ─────────────────────────────────
export const NOTIFICATION_TYPE_CONFIG: Record<
  NotificationType,
  { icon: any; color: string; bg: string; label: string }
> = {
  exam_reminder:        { icon: Calendar,       color: "#f59e0b", bg: "#fef3c7", label: "Exam Reminder"        },
  streak_alert:         { icon: Flame,          color: "#f97316", bg: "#ffedd5", label: "Streak Alert"         },
  new_message:          { icon: MessageSquare,  color: "#3b82f6", bg: "#dbeafe", label: "New Message"          },
  tutor_booking:        { icon: Video,          color: "#8b5cf6", bg: "#ede9fe", label: "Tutor Booking"        },
  session_start:        { icon: Video,          color: "#10b981", bg: "#d1fae5", label: "Session Start"        },
  session_complete:     { icon: CheckCircle,    color: "#10b981", bg: "#d1fae5", label: "Session Complete"     },
  payment_success:      { icon: CreditCard,     color: "#10b981", bg: "#d1fae5", label: "Payment Success"      },
  payment_failed:       { icon: XCircle,        color: "#ef4444", bg: "#fee2e2", label: "Payment Failed"       },
  subscription_expiring:{ icon: AlertTriangle,  color: "#f59e0b", bg: "#fef3c7", label: "Sub. Expiring"        },
  result_published:     { icon: Trophy,         color: "#8b5cf6", bg: "#ede9fe", label: "Result Published"     },
  new_content:          { icon: BookOpen,       color: "#2e8b57", bg: "#dcfce7", label: "New Content"          },
  achievement_unlocked: { icon: Trophy,         color: "#f5c842", bg: "#fef3c7", label: "Achievement"          },
  leaderboard_update:   { icon: TrendingUp,     color: "#6366f1", bg: "#e0e7ff", label: "Leaderboard"          },
  account_alert:        { icon: AlertTriangle,  color: "#ef4444", bg: "#fee2e2", label: "Account Alert"        },
  weekly_report:        { icon: BarChart3,      color: "#2e8b57", bg: "#dcfce7", label: "Weekly Report"        },
  system:               { icon: Bell,           color: "#6b7280", bg: "#f3f4f6", label: "System"               },
};

// ─── CHANNEL CONFIG ───────────────────────────────────────────
export const CHANNEL_CONFIG: Record<NotificationChannel, { icon: any; label: string; color: string }> = {
  in_app:    { icon: Bell,           label: "In-App",    color: "#2e8b57" },
  email:     { icon: Mail,           label: "Email",     color: "#3b82f6" },
  sms:       { icon: Smartphone,     label: "SMS",       color: "#8b5cf6" },
  push:      { icon: Globe,          label: "Push",      color: "#f59e0b" },
  whatsapp:  { icon: MessageSquare,  label: "WhatsApp",  color: "#10b981" },
};

// ─── MOCK DATA ────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    type: "exam_reminder",
    channel: "in_app",
    status: "unread",
    title: "JAMB Exam in 30 Days!",
    body: "Your JAMB UTME exam is scheduled for March 15th. Start your intensive preparation now to hit your target score.",
    actionUrl: "/dashboard/practice",
    metadata: { examType: "jamb", daysLeft: 30 },
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    readAt: null,
  },
  {
    id: "2",
    type: "streak_alert",
    channel: "in_app",
    status: "unread",
    title: "🔥 7-Day Streak Achieved!",
    body: "Congratulations! You've maintained a 7-day study streak. Keep the momentum going to earn bonus XP!",
    actionUrl: "/dashboard",
    metadata: { streakDays: 7 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    readAt: null,
  },
  {
    id: "3",
    type: "payment_success",
    channel: "email",
    status: "read",
    title: "Payment Successful",
    body: "Your Student Pro subscription payment of ₦2,500 was successful. Your plan is now active until next month.",
    actionUrl: "/dashboard/settings/billing",
    metadata: { amount: 2500, plan: "student_pro" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    readAt: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
  },
  {
    id: "4",
    type: "achievement_unlocked",
    channel: "in_app",
    status: "read",
    title: "🏆 Achievement Unlocked: Quiz Master",
    body: "You've answered 100 questions correctly! You've earned the 'Quiz Master' badge and 50 XP points.",
    actionUrl: "/dashboard/achievements",
    metadata: { achievement: "Quiz Master", xpEarned: 50 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    readAt: new Date(Date.now() - 1000 * 60 * 60 * 47).toISOString(),
  },
  {
    id: "5",
    type: "tutor_booking",
    channel: "in_app",
    status: "unread",
    title: "Tutor Session Confirmed",
    body: "Your session with Dr. Adeola Williams has been confirmed for Tomorrow at 4:00 PM. Prepare your questions!",
    actionUrl: "/dashboard/bookings",
    metadata: { tutorName: "Dr. Adeola Williams", sessionTime: "2024-01-20T16:00:00" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    readAt: null,
  },
  {
    id: "6",
    type: "weekly_report",
    channel: "email",
    status: "read",
    title: "Your Weekly Performance Report",
    body: "You studied 8.5 hours this week, completed 3 practice tests, and improved your average score by 5%.",
    actionUrl: "/dashboard/reports",
    metadata: { weekEnding: "2024-01-14", hoursStudied: 8.5, improvement: 5 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    readAt: new Date(Date.now() - 1000 * 60 * 60 * 71).toISOString(),
  },
  {
    id: "7",
    type: "leaderboard_update",
    channel: "in_app",
    status: "unread",
    title: "New Leaderboard Rank!",
    body: "You've climbed to #128 on the national leaderboard. You're now in the top 5% of all students!",
    actionUrl: "/dashboard/leaderboard",
    metadata: { rank: 128, percentile: 95 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    readAt: null,
  },
  {
    id: "8",
    type: "new_content",
    channel: "in_app",
    status: "read",
    title: "New Practice Questions Available",
    body: "50 new Physics past questions from 2024 WAEC have been added to the question bank. Try them now!",
    actionUrl: "/dashboard/practice",
    metadata: { subject: "Physics", count: 50 },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    readAt: new Date(Date.now() - 1000 * 60 * 60 * 95).toISOString(),
  },
  {
    id: "9",
    type: "subscription_expiring",
    channel: "email",
    status: "unread",
    title: "Subscription Expiring in 3 Days",
    body: "Your Student Pro plan expires on January 25th. Renew now to keep access to all premium features.",
    actionUrl: "/dashboard/settings/billing",
    metadata: { daysLeft: 3, plan: "student_pro" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    readAt: null,
  },
  {
    id: "10",
    type: "session_complete",
    channel: "in_app",
    status: "archived",
    title: "Session Complete — Well Done!",
    body: "You completed a 45-minute Physics session with Dr. Emeka. Your next session is in 2 days.",
    actionUrl: "/dashboard/sessions",
    metadata: { duration: 45, subject: "Physics" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    readAt: new Date(Date.now() - 1000 * 60 * 60 * 119).toISOString(),
  },
];
