POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "firstName": "Amina",
  "lastName": "Ibrahim",
  "middleName": "Blessing",
  "email": "amina.ibrahim@example.com",
  "phoneNumber": "+2348023456789",
  "password": "StrongP@ss123!",
  "gender": "female",
  "dateOfBirth": "2007-07-22",
  "stateOfResidence": "Federal Capital Territory",
  "lga": "Municipal",
  "role": "student",
  "skipEmailVerification": true
}