POST http://localhost:5000/api/v1/auth/refresh
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMTdjMWU5Zi1mMjI3LTQ1MTEtYTc2Mi00MDlmMzAwMDU0N2YiLCJqdGkiOiI1YTFiYWFhNTI4YWFlOGI3OWMzMDRmZTk4ZjUxZjA4NGE4N2Y5NzhiYjFjMGY5NThjYzA0OWNhYmVhODZhNDM0IiwiaWF0IjoxNzc5MDQyOTYyLCJleHAiOjE3ODE2MzQ5NjIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.5xM_8B3GCHkbanuLZiGLOPaiBvJ1PbNHF7A_cXYk9xQ"
}