POST http://localhost:5000/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmU1NTc1Yi1kZWI1LTRiYzctYjQ5MC02ODE0OGY3MWM3ZWYiLCJyb2xlIjoic3R1ZGVudCIsImp0aSI6Ijc2NDQ5NWVkOGM1ODk3ODIyN2JmNDQ3NjFiMjMyNWNmNDFkYzk3NTBhMTc5NTdhYjRkZGNmYTI5NTUzZTA5N2MiLCJpYXQiOjE3Nzg1MjY2MDcsImV4cCI6MTc3ODUzMDIwNywiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.dDfm7aCSy3Wf2gNIB5scfDBjmBQ7tyiVOXLhEhlX2GQ
content-type: application/json
