import {
  Exam,
  ClassExamStats,
  Question,
  QuestionType,
  DifficultyLevel,
  ExamStatus,
  Term,
} from "./types";

export const MOCK_QUESTIONS: Record<string, Question[]> = {
  "exam-001": [
    {
      id: "q-001",
      examId: "exam-001",
      type: QuestionType.MCQ,
      category: "Algebra",
      questionText: "Solve for x: 2x + 5 = 13",
      options: ["x = 3", "x = 4", "x = 5", "x = 6"],
      correctAnswer: "x = 4",
      explanation: "Subtract 5 from both sides: 2x = 8, then divide by 2: x = 4",
      marks: 5,
      difficulty: DifficultyLevel.EASY,
      orderIndex: 1,
      isActive: true,
      createdAt: new Date("2026-06-01"),
      updatedAt: new Date("2026-06-01"),
    },
    {
      id: "q-002",
      examId: "exam-001",
      type: QuestionType.MCQ,
      category: "Algebra",
      questionText: "What is the value of 3² + 4²?",
      options: ["7", "12", "25", "49"],
      correctAnswer: "25",
      explanation: "3² = 9, 4² = 16, 9 + 16 = 25",
      marks: 5,
      difficulty: DifficultyLevel.EASY,
      orderIndex: 2,
      isActive: true,
      createdAt: new Date("2026-06-01"),
      updatedAt: new Date("2026-06-01"),
    },
    {
      id: "q-003",
      examId: "exam-001",
      type: QuestionType.THEORY,
      category: "Algebra",
      questionText: "Solve the quadratic equation: x² - 5x + 6 = 0. Show all working.",
      options: undefined,
      correctAnswer: "x = 2 or x = 3",
      explanation: "Factorize: (x - 2)(x - 3) = 0, therefore x = 2 or x = 3",
      marks: 10,
      difficulty: DifficultyLevel.MEDIUM,
      orderIndex: 3,
      isActive: true,
      createdAt: new Date("2026-06-01"),
      updatedAt: new Date("2026-06-01"),
    },
  ],
  "exam-002": [
    {
      id: "q-004",
      examId: "exam-002",
      type: QuestionType.MCQ,
      category: "Mechanics",
      questionText: "What is Newton's first law of motion also known as?",
      options: [
        "Law of Inertia",
        "Law of Acceleration",
        "Action-Reaction Law",
        "Law of Gravitation",
      ],
      correctAnswer: "Law of Inertia",
      explanation:
        "Newton's first law is the Law of Inertia - an object at rest stays at rest unless acted upon by an external force.",
      marks: 5,
      difficulty: DifficultyLevel.EASY,
      orderIndex: 1,
      isActive: true,
      createdAt: new Date("2026-06-02"),
      updatedAt: new Date("2026-06-02"),
    },
    {
      id: "q-005",
      examId: "exam-002",
      type: QuestionType.PRACTICAL,
      category: "Mechanics",
      questionText:
        "Describe an experiment to verify Hooke's law. Include apparatus, procedure, and observations.",
      options: undefined,
      correctAnswer: "Detailed experimental description",
      explanation: "Students should describe using a spring, weights, ruler, and graph plotting.",
      marks: 15,
      difficulty: DifficultyLevel.HARD,
      orderIndex: 2,
      isActive: true,
      createdAt: new Date("2026-06-02"),
      updatedAt: new Date("2026-06-02"),
    },
  ],
};

export const MOCK_EXAMS: Exam[] = [
  {
    id: "exam-001",
    schoolId: "school-001",
    classId: "class-001",
    className: "SS3 Science",
    classArm: "A",
    subject: "Mathematics",
    title: "First Term Mathematics Examination",
    term: Term.FIRST,
    termYear: "2025/2026",
    description: "Comprehensive mathematics exam covering algebra, geometry, and statistics.",
    totalMarks: 100,
    totalQuestions: 3,
    durationMinutes: 90,
    startDate: new Date("2026-06-15T09:00:00"),
    endDate: new Date("2026-06-15T10:30:00"),
    instruction: "Answer all questions. Show all working where necessary.",
    status: ExamStatus.PUBLISHED,
    questions: MOCK_QUESTIONS["exam-001"],
    totalStudents: 35,
    submittedCount: 28,
    averageScore: 72.5,
    passingScore: 40,
    isActive: true,
    createdAt: new Date("2026-06-01"),
    updatedAt: new Date("2026-06-01"),
  },
  {
    id: "exam-002",
    schoolId: "school-001",
    classId: "class-001",
    className: "SS3 Science",
    classArm: "A",
    subject: "Physics",
    title: "First Term Physics Assessment",
    term: Term.FIRST,
    termYear: "2025/2026",
    description: "Physics exam covering mechanics and thermodynamics.",
    totalMarks: 100,
    totalQuestions: 2,
    durationMinutes: 120,
    startDate: new Date("2026-06-20T10:00:00"),
    endDate: new Date("2026-06-20T12:00:00"),
    instruction: "Answer all questions. Show all working.",
    status: ExamStatus.PUBLISHED,
    questions: MOCK_QUESTIONS["exam-002"],
    totalStudents: 35,
    submittedCount: 0,
    averageScore: undefined,
    passingScore: 40,
    isActive: true,
    createdAt: new Date("2026-06-02"),
    updatedAt: new Date("2026-06-02"),
  },
  {
    id: "exam-003",
    schoolId: "school-001",
    classId: "class-001",
    className: "SS3 Science",
    classArm: "A",
    subject: "Chemistry",
    title: "Chemistry Quiz - Organic Chemistry",
    term: Term.FIRST,
    termYear: "2025/2026",
    description: "Quiz on organic chemistry concepts.",
    totalMarks: 50,
    totalQuestions: 0,
    durationMinutes: 30,
    startDate: new Date("2026-06-25T11:00:00"),
    endDate: new Date("2026-06-25T11:30:00"),
    instruction: "Answer all questions.",
    status: ExamStatus.DRAFT,
    questions: [],
    totalStudents: 35,
    submittedCount: 0,
    averageScore: undefined,
    passingScore: 25,
    isActive: true,
    createdAt: new Date("2026-06-05"),
    updatedAt: new Date("2026-06-05"),
  },
  {
    id: "exam-004",
    schoolId: "school-001",
    classId: "class-002",
    className: "SS3 Art",
    classArm: "B",
    subject: "English",
    title: "First Term English Literature",
    term: Term.FIRST,
    termYear: "2025/2026",
    description: "Literature exam on prescribed texts.",
    totalMarks: 80,
    totalQuestions: 0,
    durationMinutes: 90,
    startDate: new Date("2026-06-18T09:00:00"),
    endDate: new Date("2026-06-18T10:30:00"),
    instruction: "Answer three questions from section A and one from section B.",
    status: ExamStatus.DRAFT,
    questions: [],
    totalStudents: 28,
    submittedCount: 0,
    averageScore: undefined,
    passingScore: 30,
    isActive: true,
    createdAt: new Date("2026-06-03"),
    updatedAt: new Date("2026-06-03"),
  },
];

export const MOCK_CLASS_EXAM_STATS: ClassExamStats[] = [
  {
    classId: "class-001",
    className: "SS3 Science",
    classArm: "A",
    totalExams: 3,
    publishedExams: 2,
    completedExams: 0,
    averageScore: 72.5,
    totalStudents: 35,
  },
  {
    classId: "class-002",
    className: "SS3 Art",
    classArm: "B",
    totalExams: 1,
    publishedExams: 0,
    completedExams: 0,
    averageScore: 0,
    totalStudents: 28,
  },
  {
    classId: "class-003",
    className: "SS3 Commercial",
    classArm: null,
    totalExams: 0,
    publishedExams: 0,
    completedExams: 0,
    averageScore: 0,
    totalStudents: 30,
  },
  {
    classId: "class-004",
    className: "SS2 Science",
    classArm: "A",
    totalExams: 0,
    publishedExams: 0,
    completedExams: 0,
    averageScore: 0,
    totalStudents: 38,
  },
  {
    classId: "class-005",
    className: "JSS3",
    classArm: "A",
    totalExams: 0,
    publishedExams: 0,
    completedExams: 0,
    averageScore: 0,
    totalStudents: 42,
  },
];

export const getExamById = (id: string): Exam | undefined => {
  return MOCK_EXAMS.find((exam) => exam.id === id);
};

export const getExamsByClassId = (classId: string): Exam[] => {
  return MOCK_EXAMS.filter((exam) => exam.classId === classId);
};

export const getExamsBySubject = (subject: string): Exam[] => {
  return MOCK_EXAMS.filter((exam) => exam.subject.toLowerCase().includes(subject.toLowerCase()));
};
